# J'ai séparé cet import afin de ne pas avoir le préfixe /blog lors de l'import
SdzBlogBundle:
    resource: "@SdzBlogBundle/Resources/config/routing_accueil.yml"
    prefix:   /

SdzBlogBundlePrefix:
    resource: "@SdzBlogBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/blog
    requirements:
        _locale: en|fr # les locales disponibles, séparées par des pipes « | »

# SdzBlogBundle:
    # resource: "@SdzBlogBundle/Resources/config/routing.yml"
    # prefix:   /{_locale}/blog
    # requirements:
        # _locale: en|fr # les locales disponibles, séparées par des pipes « | »

login:
    pattern:   /login
    defaults:  { _controller: SdzUserBundle:Security:login }

login_check:
    pattern:   /login_check
    defaults:  { _controller: SdzUserBundle:Security:login }

logout:
    pattern:   /logout
    defaults:  { _controller: SdzUserBundle:Security:login }

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
