sdz_blog_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: SdzBlogBundle:Default:index }

sdzblog_accueil:
    path:      /{page}
    defaults:  { _controller: SdzBlogBundle:Blog:index, page: 1 }
    requirements:
        page:  \d*
    
sdzblog_voir:
    path:      /article/{id}
    defaults:  { _controller: SdzBlogBundle:Blog:voir }
    requirements:
        id:  \d+
    
sdzblog_ajouter:
    path:      /ajouter
    defaults:  { _controller: SdzBlogBundle:Blog:ajouter }

sdzblog_modifier:
    pattern:   /modifier/{id}
    defaults:  { _controller: SdzBlogBundle:Blog:modifier }
    requirements:
        id:  \d+

sdzblog_supprimer:
    pattern:   /supprimer/{id}
    defaults:  { _controller: SdzBlogBundle:Blog:supprimer }
    requirements:
        id:  \d+

sdzblog_voir_slug:
    path:     /{annee}/{slug}.{format}
    defaults:  { _controller: SdzBlogBundle:Blog:voirSlug, format: html }
    requirements:
        annee:  \d{4}
        format: html|xml

sdzblog_modifier_image:
    path:      /modifierimage/{id}
    defaults:  { _controller: SdzBlogBundle:Blog:modifierImage }

sdzblog_test:
    path:      /test
    defaults:  { _controller: SdzBlogBundle:Blog:test }

sdzblog_liste:
    path:      /{date}
    defaults:  { _controller: SdzBlogBundle:Blog:voirListe }